<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGyhiUl3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGyhiUl3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGyhiUl3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGyhiUl3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGyhiUl3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GyhiUl3',
    'container.build_id' => 'fa508928',
    'container.build_time' => 1554838887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGyhiUl3');
