<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPSksISO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPSksISO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPSksISO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPSksISO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPSksISO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PSksISO',
    'container.build_id' => 'a3d0fd75',
    'container.build_time' => 1553632571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPSksISO');
